Metal press rendersync
BluSunrize/ImmersiveEngineering pull request #4271
Opened 2020-09-03 09:02 UTC by MalkContent

gets rid of a lot of magic numbers in MetalPressRenderer and MetalPressTileEntity and centralizes them in MetalPressRenderer to allow for easier manipulation of the machines operating speed/behavior

added code to automatically speed up the transport and press speeds for processes with maxTicks smaller than the standard operating speed allow by default

removed usage of partialTicks because of at seemingly randomly timed jaggy animation of the items on the conveyor belt, more noticably at faster processing speeds
sadly could not find a solution to make it use partialTicks properly :/

2020-09-04 15:58 UTC, SkySom requested changes

2020-09-04 15:58 UTC, SkySom commented on src/main/java/blusunrize/immersiveengineering/client/render/tile/MetalPressRenderer.java
> +		System.out.println(partialTicks);
println needs to be removed.

2020-09-04 17:47 UTC, MalkContent commented on src/main/java/blusunrize/immersiveengineering/client/render/tile/MetalPressRenderer.java
> +		System.out.println(partialTicks);
ty, good catch

2020-09-29 03:24 UTC, SkySom approved these changes

2020-10-04 08:33 UTC, BluSunrize commented
This should be obsolete due to #4272, correct?

2020-10-04 13:24 UTC, MalkContent commented
correct, it's included in #4272

2020-10-04 14:39 UTC, closed without merging