Fix jerrycans disappearing when filling empty buckets, closes #4482
BluSunrize/ImmersiveEngineering pull request #4493
Opened 2020-12-10 20:48 UTC by nhalbleiter

I *hope* this is an acceptable fix; it seems to me that the person writing it before just got the operator inverted.

2020-12-15 15:40 UTC, malte0811 requested changes
That fix is definitely not correct. `getFluidHandler` returns a `LazyOptional`, which (both by convention and in practice) is non-null. So comparing that value to null is meaningless. The proper fix would probably be something involving `LazyOptional.isPresent()`.

Make sure to also test your fix with filling a jerrycan from another jerrycan, that case currently seems to be broken as well.

2021-01-16 20:41 UTC, ConductiveFoam commented
Came up with a different implementation for `getRemainingItems`: Keep only the first recognized Jerrycan, since that's the one that `getCraftingResult` uses as a source of fluid. All other items get discarded as before; this is also is why 9515e4d restricts recipes to two items, before one could lose items by filling more of the slots.
Now Jerrycan-Jerrycan filling works too

Hope this is better!

2021-01-23 10:16 UTC, malte0811 reviewed
Looks good now (aside from some minor formatting problems), and seems to fix the problem it's intended to fix. There's another problem with this recipe (filling by non-1000-mB-amounts is handled by essentially using a side-channel, which seems to be broken), but that's not related to the problem described in #4482. I'll look into that problem later, unless you want to include that in this PR?

2021-01-23 10:16 UTC, malte0811 commented on src/main/java/blusunrize/immersiveengineering/common/crafting/JerrycanRefillRecipe.java
> +		{
Formatting (the braces should be removed)

2021-01-23 10:16 UTC, malte0811 commented on src/main/java/blusunrize/immersiveengineering/common/crafting/JerrycanRefillRecipe.java
> +	private int countOccupiedSlots(IInventory inv) {
Formatting (brace should be on the next line)

2021-01-23 10:16 UTC, malte0811 commented on src/main/java/blusunrize/immersiveengineering/common/crafting/JerrycanRefillRecipe.java
>  				remaining.set(i, ItemStack.EMPTY);
IMO something like
```java
if (…)
    foundJerrycan = true;
else
    remaining.set(i, ItemStack.EMPTY);
```
would be nicer here.

2021-01-23 12:07 UTC, ConductiveFoam commented
Glad it looks good!
Fixed the formatting problems.

I don't get what other problem you are referring to, filling odd amounts works for me. The tooltip in the crafting grid sometimes is off, the items themselves get processed fine however. Can you elaborate? I'm happy to help out some more

2021-03-01 19:15 UTC, merged

2021-03-01 19:17 UTC, BluSunrize commented
...shit I merged this into the wrong branch