[1.16.4] IE is not showing correct information for OneProbe
BluSunrize/ImmersiveEngineering pull request #4553
Opened 2021-01-03 12:23 UTC by RobustProgram

Went through 1.12.2 codebase and converted the OneProbeHelper file to be up to date with the latest Forge, IE and TheOneProbe API.

Tested and confirm to work with both client and server.

2021-01-03 12:26 UTC, RobustProgram commented
Regarding the checks failing, Forge's server seems to down as the time of this comment.

2021-01-03 12:50 UTC, BluSunrize requested changes
I've highlighted some of the stylistic changes I'd like to see fixed. Overall you seem to be breaking a few lines to keep them to a much lower length than we necessitate. I prefer having code in one line (unless it goes off my screen, 200+ characters or smth).

I am also not sure how much I like all these static classes in there. It may be more prudent to make a `top` package, similar to the `jei` one, and put these classes in there separately.

After making those adjustments, please also build the project, and test it in an instance without TOP installed to verify that we are not experiencing any forced dependencies

2021-01-03 12:50 UTC, BluSunrize commented on src/main/java/blusunrize/immersiveengineering/common/util/compat/OneProbeCompatModule.java
> + * BluSunrize, RobustProgram
The header should only feature the product owner, not the file author.

2021-01-03 12:50 UTC, BluSunrize commented on src/main/java/blusunrize/immersiveengineering/common/util/compat/OneProbeCompatModule.java
> +			IProbeHitData data
Please condense these into fewer lines (two or three), this does not match out usual codestyle

2021-01-03 12:50 UTC, BluSunrize commented on src/main/java/blusunrize/immersiveengineering/common/util/compat/OneProbeCompatModule.java
> +			IProbeHitData data
Same here, please condense the parameter list

2021-01-03 12:50 UTC, BluSunrize commented on src/main/java/blusunrize/immersiveengineering/common/util/compat/OneProbeCompatModule.java
> +			IProbeHitEntityData data
As above

2021-01-03 12:50 UTC, BluSunrize commented on src/main/java/blusunrize/immersiveengineering/common/util/compat/OneProbeCompatModule.java
> +			IProbeHitData data
As above

2021-01-03 12:50 UTC, BluSunrize commented on src/main/java/blusunrize/immersiveengineering/common/util/compat/OneProbeCompatModule.java
> +			IProbeHitData data
As above

2021-01-03 12:50 UTC, BluSunrize commented on src/main/java/blusunrize/immersiveengineering/common/util/compat/OneProbeCompatModule.java
> +				{
Parenthesis for this loop are not necessary, since it only contains the condition

2021-01-03 12:50 UTC, BluSunrize commented on src/main/java/blusunrize/immersiveengineering/common/util/compat/OneProbeCompatModule.java
> +			IProbeHitData data
As above

2021-01-03 12:50 UTC, BluSunrize commented on src/main/java/blusunrize/immersiveengineering/common/util/compat/OneProbeCompatModule.java
> +							data.getPos().offset(teslaCoil.getFacing(), -1));
This does not need to be split. We do not enforce line lengths (unless they are ridiculously long).

2021-01-03 13:41 UTC, RobustProgram commented
As per your request I have made the following updates to the PR.

**Style Changes**
I updated most of the code to fit the style of the codebase. The only potential point of contention is with the `addProbeInfo` function parameters as I reduced them to two lines instead of one line. This purely only because my screen can only display around ~120 lines and since I may need to help maintain these files in the future, I opted to place them into two lines for future convenience. However, I am more than happy to make them into one liners.

**Regarding static classes**
I considered your comment about using static classes and followed your suggestion on creating a `top` package within the `compat` package and placed all classes separately in there.

**Testing**
I also tested this build with the following setups,
- SP with only IE
- SP with IE and TOP
- MP with only IE
- MP with IE and TOP

The build works without any issues for all 4 setups.

Thank you

2021-01-11 14:27 UTC, BluSunrize commented
You fixed the licensing, but you are the author, so the `@author` tag at the start of classes should list you, not me =P

2021-01-26 00:44 UTC, RobustProgram commented
I updated the licencing for all of the files to reflect the standard of the project.

Cheers mate!

2021-02-01 16:04 UTC, BluSunrize commented
Let's see if this PR works for .5

2021-02-01 16:04 UTC, BluSunrize commented
It sure don't. That's a shame. I'll have to merge this manually.

2021-02-01 16:26 UTC, BluSunrize commented
I've pulled this in manually now!

2021-02-01 16:26 UTC, closed without merging